import JSZip from 'jszip';
import type { WPXDomNode, WPXDomPage, WPXDomProject } from '../types';
import { createProductionReport } from '../production';
import { collectDomClassMap } from '../tailwind';

const esc = (value: string) => value.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const routePath = (path: string) => path === '/' ? 'app/page.tsx' : `app/${path.replace(/^\//, '').replace(/\/$/, '')}/page.tsx`;
const attrs = (node: WPXDomNode) => [`data-wpx-node-id=\"${node.id}\"`, node.className ? `className=\"${node.className.replace(/\"/g, '&quot;')}\"` : ''].filter(Boolean).join(' ');

function tagFor(node: WPXDomNode) {
  if (node.type === 'root') return 'main';
  if (node.type === 'heading') return 'h1';
  if (node.type === 'text') return 'p';
  if (node.type === 'button') return 'button';
  if (node.type === 'image') return 'img';
  if (node.type === 'footer') return 'footer';
  if (node.type === 'card') return 'article';
  if (node.type === 'grid' || node.type === 'stack' || node.type === 'container') return 'div';
  return 'section';
}

function nodeToJsx(node: WPXDomNode): string {
  const tag = tagFor(node);
  if (tag === 'img') return `<img ${attrs(node)} alt=\"${esc(String(node.props.alt ?? node.name))}\" src=\"${String(node.props.src ?? '/assets/wpx-placeholder.svg')}\" />`;
  return `<${tag} ${attrs(node)}>${esc(node.content ?? '')}${node.children.map(nodeToJsx).join('')}</${tag}>`;
}

function componentName(page: WPXDomPage, index: number) {
  const base = `${page.name || `Page${index}`}`.replace(/[^a-zA-Z0-9]+/g, ' ').trim().split(/\s+/).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('') || `Page${index}`;
  return `${base}Dom`;
}

function componentSource(page: WPXDomPage, index: number) {
  return `export function ${componentName(page, index)}() {\n  return (${nodeToJsx(page.root)});\n}\n`;
}

function importPrefix(page: WPXDomPage) {
  return page.path === '/' ? '..' : '../..';
}

function pageSource(project: WPXDomProject, page: WPXDomPage, index: number) {
  const name = componentName(page, index);
  const prefix = importPrefix(page);
  return `import { ${name} } from '${prefix}/components/${name}';\nimport dom from '${prefix}/data/dom.json';\n\nexport const metadata = {\n  title: ${JSON.stringify(String(page.seo?.title ?? project.name))},\n  description: ${JSON.stringify(String(page.seo?.description ?? 'Generated by WPX Studio JSON DOM Kernel'))},\n};\n\nexport default function Page() {\n  return <${name} />;\n}\n\nexport { dom };\n`;
}

export async function createNextScaffoldZip(project: WPXDomProject) {
  const zip = new JSZip();
  const report = createProductionReport(project);
  const root = zip.folder(`${project.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || 'wpx'}-next`)!;

  project.pages.forEach((page, index) => {
    root.file(routePath(page.path), pageSource(project, page, index));
    root.file(`components/${componentName(page, index)}.tsx`, componentSource(page, index));
  });
  root.file('app/layout.tsx', `import './globals.css';\nimport type { ReactNode } from 'react';\n\nexport default function RootLayout({ children }: { children: ReactNode }) {\n  return <html lang=\"en\"><body>{children}</body></html>;\n}\n`);
  root.file('app/globals.css', `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root { color-scheme: dark; }\nbody { margin: 0; background: #050505; color: #fff; font-family: system-ui, sans-serif; }\n`);
  root.file('lib/dom.ts', `import dom from '../data/dom.json';\nexport default dom;\n`);
  root.file('lib/production-report.ts', `import report from '../data/production-report.json';\nexport default report;\n`);
  root.file('data/dom.json', JSON.stringify(project.pages, null, 2));
  root.file('data/tailwind-class-map.json', JSON.stringify(collectDomClassMap(project), null, 2));
  root.file('data/production-report.json', JSON.stringify(report, null, 2));
  root.file('public/assets/wpx-placeholder.svg', `<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"800\" height=\"400\"><rect width=\"100%\" height=\"100%\" fill=\"#111\"/><text x=\"50%\" y=\"50%\" fill=\"#C6FF00\" text-anchor=\"middle\">WPX Asset</text></svg>`);
  root.file('package.json', JSON.stringify({ scripts: { dev: 'next dev', build: 'next build', start: 'next start' }, dependencies: { next: '15', react: 'latest', 'react-dom': 'latest' }, devDependencies: { tailwindcss: '^3.4.17', postcss: 'latest', autoprefixer: 'latest', typescript: 'latest', '@types/node': 'latest', '@types/react': 'latest', '@types/react-dom': 'latest' } }, null, 2));
  root.file('tailwind.config.ts', `import type { Config } from 'tailwindcss';\nconst config: Config = { content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'], theme: { extend: {} }, plugins: [] };\nexport default config;\n`);
  root.file('postcss.config.mjs', `const config = { plugins: { tailwindcss: {}, autoprefixer: {} } };\nexport default config;\n`);
  root.file('README.md', `# ${project.name} Next.js Export\n\nGenerated from WPX Studio JSON DOM. Run npm install, then npm run dev.\n\nProduction status: ${report.status}\n`);
  root.file('production-report.json', JSON.stringify(report, null, 2));
  return zip.generateAsync({ type: 'blob' });
}
