'use client';

import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { activities, aiPrompts, allLibrary, assets, motionPresets, projects, wxCategories } from '@/data/whisperx';

type PageKind = 'landing' | 'marketplace' | 'components' | 'builder' | 'motion' | 'ai' | 'assets' | 'tokens' | 'themes' | 'settings' | 'dashboard' | 'docs';
const nav = [['/', 'Home'], ['/builder', 'Builder'], ['/marketplace', 'Marketplace'], ['/studio', 'AI Studio'], ['/dashboard', 'Dashboard'], ['/docs', 'Docs']];
const cn = (...classes: Array<string | false | undefined>) => classes.filter(Boolean).join(' ');

function ThemeScript() {
  useEffect(() => {
    document.documentElement.dataset.theme = localStorage.getItem('wx-theme') || 'dark';
  }, []);
  return null;
}

function useTrap(open: boolean, onClose: () => void) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!open) return;
    const node = ref.current;
    const focusables = () => Array.from(node?.querySelectorAll<HTMLElement>('button,a,input,textarea,[tabindex]:not([tabindex="-1"])') || []);
    focusables()[0]?.focus();
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
      if (event.key === 'Tab') {
        const list = focusables();
        const first = list[0];
        const last = list[list.length - 1];
        if (!first || !last) return;
        if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
        if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, onClose]);
  return ref;
}

function Shell({ children }: { children: React.ReactNode }) {
  const [command, setCommand] = useState(false);
  const [mobile, setMobile] = useState(false);
  useEffect(() => {
    const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommand(true); } };
    window.addEventListener('keydown', key);
    return () => window.removeEventListener('keydown', key);
  }, []);
  return <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)]"><ThemeScript /><Ambient /><header className="sticky top-0 z-40 border-b border-[var(--border)] bg-[color:var(--surfaceGlass)] backdrop-blur-2xl"><nav className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-4"><Link href="/" className="text-xl font-bold tracking-[-.04em]">WHISPERX <span className="text-[var(--primary)]">Builder</span></Link><div className="hidden items-center gap-2 lg:flex">{nav.map(([href, label]) => <Link className="rounded-full px-4 py-2 text-sm text-[var(--muted)] hover:bg-[var(--surfaceSoft)] hover:text-[var(--foreground)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[var(--primary)]" href={href} key={href}>{label}</Link>)}</div><div className="flex gap-2"><button aria-label="Toggle theme" onClick={() => { const next = document.documentElement.dataset.theme === 'light' ? 'dark' : 'light'; document.documentElement.dataset.theme = next; localStorage.setItem('wx-theme', next); }} className="control">☼</button><button aria-label="Open command palette" onClick={() => setCommand(true)} className="control">⌘K</button><button aria-label="Open mobile navigation" onClick={() => setMobile(true)} className="control lg:hidden">☰</button></div></nav></header><CommandPalette open={command} onClose={() => setCommand(false)} /><Drawer title="Navigation" open={mobile} onClose={() => setMobile(false)}>{nav.map(([href, label]) => <Link onClick={() => setMobile(false)} className="panel-link" href={href} key={href}>{label}</Link>)}</Drawer><main>{children}</main><Footer /></div>;
}

function Ambient() { return <div aria-hidden="true" className="pointer-events-none fixed inset-0 -z-10 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_25%_10%,var(--primaryGlow),transparent_32%),radial-gradient(circle_at_82%_20%,var(--specialGlow),transparent_28%),linear-gradient(180deg,var(--background),var(--background))]" /><div className="absolute inset-0 opacity-[.08] [background-image:linear-gradient(var(--borderStrong)_1px,transparent_1px),linear-gradient(90deg,var(--borderStrong)_1px,transparent_1px)] [background-size:64px_64px]" /></div>; }
function Button({ children, onClick, variant = 'primary', disabled }: { children: React.ReactNode; onClick?: () => void; variant?: 'primary' | 'ghost'; disabled?: boolean }) { return <motion.button whileHover={disabled ? undefined : { y: -2 }} whileTap={disabled ? undefined : { scale: .97 }} disabled={disabled} onClick={onClick} className={cn('min-h-11 rounded-full px-5 text-sm font-semibold outline-none transition focus-visible:ring-4 focus-visible:ring-[var(--primaryGlow)]', variant === 'primary' ? 'bg-[var(--primary)] text-[var(--onPrimary)] shadow-[var(--glowPrimary)] hover:bg-[var(--primaryHover)]' : 'border border-[var(--borderStrong)] bg-[var(--surfaceGlass)] text-[var(--foreground)] hover:bg-[var(--surfaceSoft)]')}>{children}</motion.button>; }
function Card({ children, className = '', ...props }: React.ComponentProps<typeof motion.section> & { children: React.ReactNode; className?: string }) { return <motion.section {...props} initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className={cn('rounded-[32px] border border-[var(--border)] bg-[var(--surfaceGlass)] p-6 shadow-2xl shadow-black/10 backdrop-blur-2xl', className)}>{children}</motion.section>; }
function Kicker({ children }: { children: React.ReactNode }) { return <p className="font-mono text-[10px] font-semibold uppercase tracking-[.18em] text-[var(--primary)]">{children}</p>; }
function HeroTitle({ children }: { children: React.ReactNode }) { return <h1 className="mt-5 text-[clamp(48px,8vw,112px)] font-bold leading-[.95] tracking-[-.04em]">{children}</h1>; }

function CommandPalette({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [q, setQ] = useState('');
  const ref = useTrap(open, onClose);
  const commands = ['Open builder canvas', 'Search marketplace', 'Generate AI hero', 'Publish preview', 'Toggle light mode', 'Show keyboard shortcuts'];
  const matches = commands.filter((c) => c.toLowerCase().includes(q.toLowerCase()));
  return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-50 bg-black/55 p-4 pt-24" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} role="dialog" aria-modal="true" aria-label="Command palette"><motion.div ref={ref} initial={{ y: 24, scale: .97 }} animate={{ y: 0, scale: 1 }} exit={{ y: 24, scale: .97 }} className="mx-auto max-w-2xl rounded-[32px] border border-[var(--borderStrong)] bg-[var(--surfaceElevated)] p-4 shadow-2xl"><label htmlFor="command-search" className="sr-only">Search commands</label><input id="command-search" value={q} onChange={(e) => setQ(e.target.value)} className="field" placeholder="Search commands…" /> <p className="px-3 py-2 text-sm text-[var(--muted)]">{matches.length} results · Esc closes · Arrow through browser focus order</p>{matches.map((m) => <button className="panel-link" key={m} onClick={onClose}>{m}<span className="block text-xs text-[var(--muted)]">Production shortcut</span></button>)}</motion.div></motion.div>}</AnimatePresence>;
}
function Drawer({ title, open, onClose, children }: { title: string; open: boolean; onClose: () => void; children: React.ReactNode }) { const ref = useTrap(open, onClose); return <AnimatePresence>{open && <motion.div className="fixed inset-0 z-50 bg-black/50" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.aside ref={ref} role="dialog" aria-modal="true" aria-label={title} initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} className="ml-auto h-full w-[min(92vw,420px)] bg-[var(--surfaceElevated)] p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-bold">{title}</h2><button className="control" onClick={onClose}>×</button></div>{children}</motion.aside></motion.div>}</AnimatePresence>; }

function PreviewWindow() { return <Card className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-[var(--border)] p-4"><span className="flex gap-2"><i className="h-3 w-3 rounded-full bg-[var(--danger)]" /><i className="h-3 w-3 rounded-full bg-[var(--warning)]" /><i className="h-3 w-3 rounded-full bg-[var(--success)]" /></span><Kicker>Live application preview</Kicker></div><div className="grid gap-4 p-5 lg:grid-cols-[1fr_280px]"><div className="rounded-[24px] bg-[var(--surfaceSoft)] p-6"><Kicker>Canvas</Kicker><h3 className="mt-16 max-w-xl text-[clamp(38px,7vw,84px)] font-bold leading-[.9] tracking-[-.05em]">Create interfaces that feel alive.</h3><div className="mt-8 grid gap-3 sm:grid-cols-3">{['idle', 'hover', 'selected'].map((s) => <div className="rounded-2xl border border-[var(--borderStrong)] bg-[var(--surface)] p-4" key={s}>{s}</div>)}</div></div><div className="space-y-3">{['Layer panel', 'Floating toolbar', 'Inspector preview', 'Publish toast'].map((x) => <div className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4" key={x}>{x}</div>)}</div></div></Card>; }

function Landing() { return <Shell><section className="mx-auto grid min-h-[88vh] max-w-[1440px] items-center gap-10 px-6 py-16 lg:grid-cols-[.9fr_1.1fr]"><div><Kicker>Emerald Night / Amber Dawn</Kicker><HeroTitle>Premium creative operating system.</HeroTitle><p className="mt-6 max-w-2xl text-xl leading-relaxed text-[var(--muted)]">WHISPERX Builder combines architecture, editorial typography, cinematic motion, and accessible production UI into a living workspace.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/builder" className="inline-flex min-h-11 items-center rounded-full bg-[var(--primary)] px-5 text-sm font-semibold text-[var(--onPrimary)] shadow-[var(--glowPrimary)] hover:bg-[var(--primaryHover)] focus-visible:ring-4 focus-visible:ring-[var(--primaryGlow)]">Enter builder</Link><Link href="/marketplace" className="inline-flex min-h-11 items-center rounded-full border border-[var(--borderStrong)] bg-[var(--surfaceGlass)] px-5 text-sm font-semibold text-[var(--foreground)] hover:bg-[var(--surfaceSoft)] focus-visible:ring-4 focus-visible:ring-[var(--primaryGlow)]">Browse systems</Link></div></div><PreviewWindow /></section><section className="mx-auto grid max-w-[1440px] gap-5 px-6 py-16 lg:grid-cols-3">{['Product preview', 'Builder canvas', 'AI studio', 'Dashboard stats', 'Gallery showcase', 'Final CTA'].map((x, i) => <Card key={x}><Kicker>{String(i + 1).padStart(2, '0')}</Kicker><h2 className="mt-4 text-4xl font-bold tracking-[-.03em]">{x}</h2><p className="mt-3 text-[var(--muted)]">A responsive, cinematic module with loading, empty, success, error, focus, and reduced-motion behavior.</p></Card>)}</section></Shell>; }

function Builder() { const [layer, setLayer] = useState('Hero headline'); const [zoom, setZoom] = useState(100); const [viewport, setViewport] = useState('Desktop'); const [toast, setToast] = useState(''); return <Shell><section className="grid min-h-[calc(100vh-80px)] gap-4 p-4 lg:grid-cols-[260px_1fr_320px]"><Card><Kicker>Layers</Kicker>{['Hero headline', 'CTA cluster', 'Marketplace rail', 'AI result card'].map((l) => <button key={l} onClick={() => setLayer(l)} className={cn('panel-link', layer === l && 'bg-[var(--primarySoft)] text-[var(--foreground)] ring-1 ring-[var(--primary)]')}>{l}</button>)}<Button onClick={() => setToast('Published preview is live.')}>Publish</Button></Card><Card className="relative overflow-hidden"><div className="mb-4 flex flex-wrap items-center gap-2"><select aria-label="Viewport" className="field max-w-40" value={viewport} onChange={(e) => setViewport(e.target.value)}>{['Desktop', 'Tablet', 'Mobile'].map((v) => <option key={v}>{v}</option>)}</select><Button variant="ghost" onClick={() => setZoom(Math.max(50, zoom - 10))}>−</Button><Button variant="ghost" onClick={() => setZoom(100)}>Reset {zoom}%</Button><Button variant="ghost" onClick={() => setZoom(Math.min(150, zoom + 10))}>＋</Button></div><motion.div animate={{ scale: zoom / 100 }} className="origin-top rounded-[32px] border border-[var(--borderStrong)] bg-[var(--surfaceSoft)] p-8"><Kicker>{viewport} canvas / selected {layer}</Kicker><h1 className="mt-12 max-w-3xl text-[clamp(42px,7vw,92px)] font-bold leading-[.9] tracking-[-.05em]">A workspace that moves like cinema and edits like print.</h1><div className="mt-8 flex gap-3"><Button>Generate</Button><Button variant="ghost">Preview</Button></div></motion.div><div className="absolute bottom-6 left-1/2 flex -translate-x-1/2 gap-2 rounded-full border border-[var(--border)] bg-[var(--surfaceElevated)] p-2"><Button variant="ghost">Move</Button><Button variant="ghost">Frame</Button><Button variant="ghost">Text</Button></div></Card><Card><Kicker>Inspector</Kicker><label className="mt-4 block text-sm" htmlFor="opacity">Opacity for {layer}</label><input id="opacity" className="mt-2 w-full accent-[var(--primary)]" type="range" /><Button onClick={() => setToast(`Updated ${layer}.`)}>Apply property</Button><div className="mt-6 rounded-2xl bg-[var(--surfaceSoft)] p-4 text-sm text-[var(--muted)]">Command palette, preview window, publish action, selected layer state, zoom, and viewport switcher are interactive.</div></Card></section>{toast && <div role="status" className="fixed bottom-6 right-6 rounded-2xl bg-[var(--success)] p-4 font-semibold text-black shadow-2xl">{toast}</div>}</Shell>; }

function Marketplace() { const [q, setQ] = useState(''); const [cat, setCat] = useState('All'); const [preview, setPreview] = useState<(typeof allLibrary)[number] | null>(null); const filtered = allLibrary.filter((i) => (cat === 'All' || i.category === cat) && `${i.title} ${i.description} ${i.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase())); return <Shell><section className="mx-auto max-w-[1440px] px-6 py-12"><Kicker>Marketplace</Kicker><h1 className="mt-4 text-6xl font-bold tracking-[-.04em]">Install creative systems.</h1><div className="mt-6 grid gap-3 lg:grid-cols-[1fr_auto]"><label><span className="sr-only">Search marketplace</span><input className="field" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search components, templates, motion…" /></label><p className="self-center text-[var(--muted)]">{filtered.length} results</p></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{wxCategories.map((c) => <button onClick={() => setCat(c)} className={cn('chip', cat === c && 'chip-active')} key={c}>{c}</button>)}</div>{filtered.length === 0 ? <Card className="mt-8"><h2 className="text-3xl font-bold">No matching systems.</h2><p className="text-[var(--muted)]">Try a broader search or clear active chips.</p></Card> : <div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{filtered.map((i) => <Card key={i.id}><Kicker>{i.category} · {i.status}</Kicker><h2 className="mt-4 text-2xl font-bold">{i.title}</h2><p className="mt-2 line-clamp-2 text-sm text-[var(--muted)]">{i.description}</p><div className="mt-5 flex gap-2"><Button onClick={() => setPreview(i)}>Preview</Button><Button variant="ghost">Install</Button></div></Card>)}</div>}<section className="mt-12"><h2 className="text-4xl font-bold">Motion presets</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{motionPresets.slice(0, 8).map((m) => <Card key={m.id}><span className="text-3xl">{m.icon}</span><h3 className="mt-3 font-bold">{m.title}</h3><p className="text-sm text-[var(--muted)]">{m.duration}ms · {m.token}</p></Card>)}</div></section></section><Drawer title={preview?.title || 'Preview'} open={Boolean(preview)} onClose={() => setPreview(null)}>{preview && <div><Kicker>{preview.category}</Kicker><p className="mt-4 text-[var(--muted)]">{preview.description}</p><Button>Install system</Button></div>}</Drawer></Shell>; }

function Studio() { const reduce = useReducedMotion(); const [text, setText] = useState(''); const [loading, setLoading] = useState(false); const result = 'Generated premium hero with editorial hierarchy, ambient glow, keyboard-safe CTA group, and responsive canvas constraints.'; useEffect(() => { if (!loading) return; setText(''); let i = 0; const t = setInterval(() => { setText(result.slice(0, i++)); if (i > result.length) { clearInterval(t); setLoading(false); } }, reduce ? 1 : 28); return () => clearInterval(t); }, [loading, reduce]); return <Shell><section className="mx-auto grid max-w-[1440px] gap-6 px-6 py-12 lg:grid-cols-[.8fr_1.2fr]"><Card><Kicker>AI Studio</Kicker><h1 className="mt-4 text-6xl font-bold tracking-[-.04em]">Generate with context.</h1><textarea aria-label="AI prompt" className="field mt-6 min-h-40" defaultValue={aiPrompts[0].prompt} /><Button onClick={() => setLoading(true)}>Generate interface</Button><div className="mt-6 flex flex-wrap gap-2">{aiPrompts.slice(0, 5).map((p) => <button className="chip" key={p.id}>{p.title}</button>)}</div></Card><Card><Kicker>{loading ? 'AI thinking' : 'Streaming result'}</Kicker><div className="mt-5 min-h-72 rounded-[28px] bg-[var(--surfaceSoft)] p-6 font-mono text-sm leading-relaxed">{loading && !text ? <span className="animate-pulse">Synthesizing layout rhythm…</span> : text || 'Run a generation to stream production-ready output here.'}</div><Button>Apply to canvas</Button></Card></section></Shell>; }
function Dashboard() { return <Shell><section className="mx-auto max-w-[1440px] px-6 py-12"><Kicker>Dashboard</Kicker><h1 className="mt-4 text-6xl font-bold tracking-[-.04em]">Operational clarity.</h1><div className="mt-8 grid gap-5 md:grid-cols-4">{[['Projects', 8], ['Components', 60], ['Templates', 20], ['A11y score', 98]].map(([l, v]) => <Card key={l as string}><p className="text-[var(--muted)]">{l}</p><p className="mt-3 text-5xl font-bold tabular-nums">{v}</p></Card>)}</div><div className="mt-8 grid gap-5 lg:grid-cols-2"><Card><h2 className="text-3xl font-bold">Projects</h2>{projects.map((p) => <div className="panel-link" key={p.id}>{p.title}<span className="block text-xs text-[var(--muted)]">{p.status} · {p.updatedAt}</span></div>)}</Card><Card><h2 className="text-3xl font-bold">Activity feed</h2>{activities.map((a) => <div className="panel-link" key={a.id}>{a.message}<span className="block text-xs text-[var(--muted)]">{a.user} · {a.timestamp}</span></div>)}</Card></div></section></Shell>; }
function Docs() { return <Shell><section className="mx-auto grid max-w-[1440px] gap-6 px-6 py-12 lg:grid-cols-[280px_1fr]"><Card className="lg:sticky lg:top-24 lg:self-start"><Kicker>Docs</Kicker>{['Design tokens', 'Components', 'Motion', 'Code examples', 'Accessibility'].map((x) => <a className="panel-link" href={`#${x.toLowerCase().replaceAll(' ', '-')}`} key={x}>{x}</a>)}</Card><article className="space-y-6"><HeroTitle>Build notes for a cinematic operating system.</HeroTitle>{['Design tokens', 'Components', 'Motion', 'Code examples', 'Accessibility'].map((x) => <Card id={x.toLowerCase().replaceAll(' ', '-')} key={x}><Kicker>{x}</Kicker><h2 className="mt-3 text-4xl font-bold">{x} documentation preview</h2><p className="mt-3 text-[var(--muted)]">Semantic structure, focus-visible rings, reduced motion, search, drawers, command palette, skeleton, empty, error, and success states are documented as first-class product behavior.</p><pre className="mt-5 overflow-auto rounded-2xl bg-[var(--surfaceSoft)] p-4 font-mono text-sm"><code>{`<Button variant="primary" aria-label="Publish preview">Publish</Button>`}</code></pre></Card>)}</article></section></Shell>; }
function TokensPage() { return <Shell><section className="mx-auto max-w-[1440px] px-6 py-12"><HeroTitle>Tokens, assets, and themes.</HeroTitle><div className="mt-8 grid gap-4 md:grid-cols-3">{assets.map((a) => <Card key={a.id}><Kicker>{a.type}</Kicker><h2 className="text-2xl font-bold">{a.title}</h2><p className="text-[var(--muted)]">{a.thumbnail} · {a.size}</p></Card>)}</div></section></Shell>; }
function Footer() { return <footer className="border-t border-[var(--border)] px-6 py-10 text-center text-sm text-[var(--muted)]">WHISPERX Builder · Emerald Night and Amber Dawn · Client-side creative workspace</footer>; }

export function PlatformPage({ kind }: { kind: PageKind }) {
  if (kind === 'builder') return <Builder />;
  if (kind === 'marketplace' || kind === 'components' || kind === 'motion') return <Marketplace />;
  if (kind === 'ai') return <Studio />;
  if (kind === 'dashboard') return <Dashboard />;
  if (kind === 'docs') return <Docs />;
  if (kind === 'assets' || kind === 'tokens' || kind === 'themes' || kind === 'settings') return <TokensPage />;
  return <Landing />;
}
