'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { activities, aiPrompts, allLibrary, motionPresets, projects, wxCategories } from '@/data/whisperx';

type PageKind = 'landing' | 'marketplace' | 'components' | 'builder' | 'motion' | 'ai' | 'assets' | 'tokens' | 'themes' | 'settings' | 'dashboard' | 'docs';
const nav = [['/', 'Home'], ['/builder', 'Builder'], ['/marketplace', 'Marketplace'], ['/studio', 'AI Studio'], ['/dashboard', 'Dashboard'], ['/docs', 'Docs']];
const icons = ['⬡ Build', '✧ AI Magic', '▣ Templates', '✄ Components', '⌁ Publish', '▥ Analytics', '♡ Team', '✓ Success', '▷ Play', '⚙ Settings', '▤ Docs', '? Help', '⌕ Search', '▢ Lock', '⌯ Share', '⇩ Download'];
const swatches = [['Lime Green', '#C6FF00'], ['Neon Pink', '#FF2ED1'], ['Pure White', '#FFFFFF'], ['Graphite', '#0E0F12'], ['Smoke', '#16181D']];
const cn = (...classes: Array<string | false | undefined>) => classes.filter(Boolean).join(' ');

function ThemeScript() { useEffect(() => { document.documentElement.dataset.theme = localStorage.getItem('wx-theme') || 'dark'; }, []); return null; }
function Shell({ children }: { children: React.ReactNode }) { const [mobile, setMobile] = useState(false); return <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)]"><ThemeScript /><Ambient /><header className="sticky top-0 z-40 border-b border-[var(--border)] bg-black/55 backdrop-blur-2xl"><nav className="mx-auto flex max-w-[1720px] items-center justify-between px-5 py-3"><Link href="/" className="flex items-center gap-3 font-black tracking-[.22em]"><BrandMark small /> WHISPER<span className="text-[var(--pink)]">X</span><span className="hidden text-[10px] text-[var(--muted)] sm:inline">| STUDIO</span></Link><div className="hidden gap-1 lg:flex">{nav.map(([href, label]) => <Link className="rounded-xl px-3 py-2 text-xs uppercase tracking-[.12em] text-[var(--muted)] hover:bg-white/5 hover:text-white" href={href} key={href}>{label}</Link>)}</div><div className="flex gap-2"><button className="control" onClick={() => { const next = document.documentElement.dataset.theme === 'light' ? 'dark' : 'light'; document.documentElement.dataset.theme = next; localStorage.setItem('wx-theme', next); }}>Mode</button><button className="control lg:hidden" onClick={() => setMobile(!mobile)}>Menu</button></div></nav>{mobile && <div className="grid gap-1 border-t border-[var(--border)] p-4 lg:hidden">{nav.map(([href, label]) => <Link href={href} key={href} className="panel-link">{label}</Link>)}</div>}</header><main>{children}</main><footer className="mx-auto flex max-w-[1720px] items-center justify-between border-t border-[var(--border)] px-5 py-5 text-[10px] uppercase tracking-[.35em] text-[var(--muted)]"><span>WPX Studio</span><span>Minimal · Precise · Engineered · Modern · Powerful</span></footer></div>; }
function Ambient() { return <div aria-hidden className="pointer-events-none fixed inset-0 -z-10 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_18%,rgba(198,255,0,.14),transparent_26%),radial-gradient(circle_at_78%_16%,rgba(255,46,209,.16),transparent_28%),linear-gradient(180deg,#020305,#07090d)]" /><div className="absolute inset-0 opacity-[.08] [background-image:linear-gradient(rgba(255,255,255,.18)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.18)_1px,transparent_1px)] [background-size:42px_42px]" /></div>; }
function Card({ children, className = '', title, n }: { children: React.ReactNode; className?: string; title?: string; n?: string }) { return <section className={cn('wpx-card relative overflow-hidden rounded-[18px] border border-[var(--border)] bg-[linear-gradient(180deg,rgba(255,255,255,.045),rgba(255,255,255,.015))] p-4 shadow-2xl shadow-black/30', className)}>{title && <p className="mb-3 border-b border-[var(--border)] pb-2 text-[11px] font-black uppercase tracking-[.12em]"><span className="mr-2 text-[var(--lime)]">{n}</span>{title}</p>}{children}</section>; }
function Kicker({ children }: { children: React.ReactNode }) { return <p className="text-[11px] font-black uppercase tracking-[.16em] text-[var(--lime)]">{children}</p>; }
function BrandMark({ small = false }: { small?: boolean }) { return <div className={cn('brand-mark', small ? 'h-7 w-10' : 'h-40 w-64')}><span /><b /><i /></div>; }
function Ghost({ mini = false }: { mini?: boolean }) { return <div className={cn('ghostx', mini ? 'scale-[.55]' : '')}><span className="eye left" /><span className="eye right" /><span className="mouth" /><span className="badge"><BrandMark small /></span></div>; }
function Button({ children, ghost, onClick }: { children: React.ReactNode; ghost?: boolean; onClick?: () => void }) { return <button onClick={onClick} className={cn('rounded-md px-4 py-2 text-xs font-black uppercase tracking-[.08em] transition hover:-translate-y-0.5', ghost ? 'border border-[var(--borderStrong)] text-white' : 'bg-[var(--lime)] text-black shadow-[0_0_26px_rgba(198,255,0,.28)]')}>{children}</button>; }

function LogoSystem() { return <Card title="Logo System" n="01" className="min-h-[320px]"><div className="grid place-items-center rounded-2xl bg-[radial-gradient(circle,rgba(255,255,255,.08),transparent_55%)] py-8"><BrandMark /><h1 className="mt-6 text-center text-5xl font-black tracking-[.22em]">WHISPER<span className="text-[var(--pink)]">X</span></h1><p className="mt-3 text-sm font-bold uppercase tracking-[.45em] text-[var(--lime)]">Build Without Limits</p></div><div className="mt-4 grid grid-cols-4 gap-3">{['Primary', 'Icon', 'Wordmark', 'Mono'].map((x) => <div className="rounded-xl border border-[var(--border)] bg-black/35 p-3 text-center text-[10px] uppercase" key={x}><BrandMark small /><p className="mt-2">{x}</p></div>)}</div></Card>; }
function MascotPanel() { return <Card title="Mascot — GhostX" n="02"><div className="grid items-center gap-5 md:grid-cols-[.75fr_1fr]"><div><h2 className="text-3xl font-black leading-tight">Your <span className="text-[var(--pink)]">creative</span><br /><span className="text-[var(--lime)]">sidekick.</span></h2><p className="mt-5 max-w-xs text-sm leading-6 text-[var(--muted)]">GhostX brings clarity, curiosity, and a spark of mischief to every step of creation.</p><ul className="mt-5 space-y-2 text-sm">{['☺ Friendly', '✧ Clever', '?? Curious', '∞ Limitless'].map((x) => <li key={x}>{x}</li>)}</ul></div><Ghost /></div><div className="mt-4 grid grid-cols-5 gap-2">{['Wave', 'Point', 'Think', 'Create', 'Fly'].map((x) => <div className="rounded-xl border border-[var(--border)] p-2 text-center text-[10px] uppercase" key={x}><Ghost mini /><p>{x}</p></div>)}</div></Card>; }
function ColorTypography() { return <div className="grid gap-3"><Card title="Color System" n="03"><div className="grid grid-cols-5 gap-3">{swatches.map(([name, color]) => <div key={name}><div className="h-14 rounded-md border border-[var(--borderStrong)]" style={{ background: color }} /><p className="mt-2 text-[10px] uppercase">{name}</p><p className="font-mono text-[10px] text-[var(--muted)]">{color}</p></div>)}</div><div className="mt-4 h-8 rounded-md bg-[linear-gradient(90deg,var(--lime),#314600,var(--pink),#ffb6e8)]" /></Card><Card title="Typography System" n="04"><div className="grid gap-4 md:grid-cols-3"><div><p className="text-6xl font-black">Aa</p><b>Clash Display</b></div><div><p className="text-6xl">Aa</p><b>Inter</b></div><div className="space-y-1 text-sm text-[var(--muted)]"><p>Light</p><p>Regular</p><p className="font-semibold text-white">Semibold</p><p className="font-black text-white">Bold</p></div></div></Card></div>; }
function IconSystem() { return <Card title="Icon System" n="05"><div className="grid grid-cols-4 gap-4">{icons.map((x, i) => <div className="text-center" key={x}><p className={cn('text-3xl', i % 2 ? 'text-[var(--pink)]' : 'text-[var(--lime)]')}>{x.split(' ')[0]}</p><p className="mt-1 text-[10px]">{x.split(' ').slice(1).join(' ')}</p></div>)}</div></Card>; }
function ControlsShowcase() { return <Card title="Components" n="09"><div className="grid gap-4 md:grid-cols-3"><div className="space-y-3"><Button>Publish Now</Button><Button ghost>Explore</Button><Button ghost>Learn More</Button></div><div className="space-y-3"><input className="field" placeholder="Search components..." /><select className="field"><option>Choose a category</option></select><label className="flex gap-2 text-xs"><input type="checkbox" defaultChecked /> Enable advanced mode</label></div><div className="rounded-xl border border-[var(--lime)] bg-black/40 p-4 shadow-[0_0_28px_rgba(198,255,0,.22)]"><Kicker>Hover Card</Kicker><h3 className="mt-2 text-xl font-black">AI Hero Section</h3><p className="mt-2 text-xs text-[var(--muted)]">Premium component with assistance.</p><div className="mt-4 flex gap-2"><span className="chip-active rounded px-2 py-1 text-[10px]">Premium</span><span className="rounded border border-[var(--border)] px-2 py-1 text-[10px]">AI</span></div></div></div></Card>; }
function BuilderPreview() { return <Card title="Builder Workspace Preview" n="14" className="lg:col-span-2"><div className="grid min-h-[300px] gap-3 lg:grid-cols-[170px_1fr_220px]"><aside className="rounded-xl border border-[var(--border)] p-3 text-xs text-[var(--muted)]">{['Hero Section', 'Character', 'Headline', 'Text', 'Button', 'Image', 'Background'].map((x, i) => <p className={cn('rounded-md p-2', i === 0 && 'bg-white/10 text-white')} key={x}>▸ {x}</p>)}</aside><div className="relative rounded-xl border border-[var(--borderStrong)] bg-[radial-gradient(circle_at_70%_45%,rgba(198,255,0,.2),transparent_22%),#080a0f] p-8"><h2 className="max-w-sm text-5xl font-black leading-none">Design<br />Without<br /><span className="text-[var(--pink)]">Limits.</span></h2><div className="absolute right-8 top-8"><Ghost mini /></div><div className="absolute bottom-4 left-4 flex gap-2"><Button>Start Building</Button><Button ghost>Preview</Button></div></div><aside className="rounded-xl border border-[var(--border)] p-3 text-xs"><Kicker>Inspector</Kicker>{['X 240', 'Y 140', 'W 480', 'H 120', 'Opacity 100'].map((x) => <p className="mt-3 rounded-md bg-white/5 p-2" key={x}>{x}</p>)}</aside></div></Card>; }
function DashCard() { return <Card title="Dashboard" n="13"><div className="grid grid-cols-4 gap-2">{[['Projects','1,248'],['Components','2,845'],['Templates','428'],['Rate','98%']].map(([l,v]) => <div className="rounded-xl border border-[var(--border)] p-3" key={l}><p className="text-[10px] text-[var(--muted)]">{l}</p><b className="text-2xl">{v}</b><p className="text-[10px] text-[var(--lime)]">+18.2%</p></div>)}</div><div className="mt-5 grid gap-4 md:grid-cols-[180px_1fr]"><div className="aspect-square rounded-full border-[18px] border-[var(--pink)] border-r-[var(--lime)] grid place-items-center text-2xl font-black">78%</div><div className="space-y-2">{activities.slice(0,4).map((a) => <p className="rounded-lg bg-white/5 p-2 text-xs" key={a.id}>{a.message}</p>)}</div></div></Card>; }

function Landing() { return <Shell><section className="mx-auto grid max-w-[1720px] gap-3 p-3 lg:grid-cols-[1fr_1.1fr_1fr_.65fr]"><LogoSystem /><MascotPanel /><ColorTypography /><IconSystem /><ControlsShowcase /><DashCard /><Card title="Mobile Preview" n="15"><div className="mx-auto max-w-[210px] rounded-[30px] border border-[var(--borderStrong)] bg-black p-4 text-center"><Ghost mini /><h2 className="mt-4 text-2xl font-black">Build Without <span className="text-[var(--lime)]">Limits.</span></h2><Button>Get Started Free</Button></div></Card><BuilderPreview /><Card title="Promotional Banners" n="16" className="lg:col-span-2"><div className="grid gap-3 md:grid-cols-4">{['AI That Designs With You.', '100+ Production Components', 'Publish Anywhere. One Click.', 'Create Faster. Ship Sooner.'].map((x) => <div className="rounded-xl border border-[var(--border)] p-4" key={x}><h3 className="text-xl font-black">{x}</h3></div>)}</div></Card><Card title="Visual Style Guide" n="17" className="lg:col-span-2"><div className="grid grid-cols-5 gap-3">{['Neon Glow', 'Smoke Effect', 'Glass Morphism', 'Grid Pattern', 'Gradient Mesh'].map((x, i) => <div className="h-24 rounded-xl border border-[var(--border)] p-3 text-xs" key={x} style={{background: i===0?'linear-gradient(135deg,#ff2ed1,#111,#c6ff00)':undefined}}>{x}</div>)}</div></Card></section></Shell>; }
function Builder() { const [layer, setLayer] = useState('Hero / 01'); const [toast, setToast] = useState(''); return <Shell><section className="mx-auto grid max-w-[1720px] gap-3 p-3 lg:grid-cols-[280px_1fr_320px]"><Card title="Layers" n="01">{['Hero / 01','Navigation','CTA Button','GhostX','Features','Footer'].map((l) => <button className={cn('panel-link', layer===l && 'bg-[var(--lime)]/15 text-white ring-1 ring-[var(--lime)]')} onClick={() => setLayer(l)} key={l}>{l}</button>)}</Card><BuilderPreview /><Card title="Inspector" n="02"><Kicker>{layer}</Kicker>{['Position','Size','Auto Layout','Constraints','Effects'].map((x)=> <div className="mt-3 rounded-xl border border-[var(--border)] p-3" key={x}>{x}<input className="mt-2 w-full accent-[var(--pink)]" type="range" /></div>)}<Button onClick={() => setToast(`${layer} polished and locked.`)}>Apply to Canvas</Button></Card>{toast && <div className="fixed bottom-6 right-6 rounded-xl border border-[var(--lime)] bg-black p-4 text-sm text-[var(--lime)]">{toast}</div>}</section></Shell>; }
function Marketplace() { const [q, setQ] = useState(''); const [cat, setCat] = useState('All'); const filtered = allLibrary.filter((i) => (cat === 'All' || i.category === cat) && `${i.title} ${i.description}`.toLowerCase().includes(q.toLowerCase())); return <Shell><section className="mx-auto max-w-[1720px] p-3"><Card title="Marketplace Preview" n="01"><input className="field" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search components, templates..." /><div className="mt-3 flex gap-2 overflow-x-auto">{wxCategories.map((c) => <button className={cn('chip', cat===c && 'chip-active')} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="mt-5 grid gap-3 md:grid-cols-3 xl:grid-cols-5">{filtered.slice(0,15).map((i) => <div className="rounded-xl border border-[var(--border)] bg-black/35 p-4" key={i.id}><Ghost mini /><Kicker>{i.category}</Kicker><h2 className="mt-2 font-black">{i.title}</h2><p className="mt-2 line-clamp-2 text-xs text-[var(--muted)]">{i.description}</p></div>)}</div></Card></section></Shell>; }
function Studio() { const [text, setText] = useState(''); const output = useMemo(() => 'Created a modern hero section with gradient background, GhostX mascot, accessible CTA group, responsive lockspec grid, and production-ready tokens.', []); return <Shell><section className="mx-auto grid max-w-[1720px] gap-3 p-3 lg:grid-cols-[.8fr_1.2fr]"><Card title="AI Studio" n="01"><textarea className="field min-h-44" defaultValue={aiPrompts[0]?.prompt} /><Button onClick={() => setText(output)}>Generate Section</Button></Card><Card title="Generated Result" n="02"><p className="min-h-44 rounded-xl bg-black/40 p-5 font-mono text-sm">{text || 'GhostX is thinking…'}</p><Button>Apply to Canvas</Button></Card></section></Shell>; }
function Dashboard() { return <Shell><section className="mx-auto max-w-[1720px] p-3"><DashCard /><div className="mt-3 grid gap-3 md:grid-cols-2">{projects.map((p) => <Card key={p.id}><h2 className="text-2xl font-black">{p.title}</h2><p className="text-[var(--muted)]">{p.status} · {p.updatedAt}</p></Card>)}</div></section></Shell>; }
function Docs() { return <Shell><section className="mx-auto max-w-[1720px] p-3"><Card title="Studio Design Bible" n="01"><h1 className="text-6xl font-black">Product Foundation</h1><div className="mt-6 grid gap-3 md:grid-cols-2">{['Product architecture', 'Module overview', 'User workflow', 'Lockspec tokens'].map((x, i) => <Card title={x} n={`0${i+2}`} key={x}><p className="text-[var(--muted)]">Production rules, design tokens, user flows, and acceptance criteria for pixel-perfect WHISPERX surfaces.</p></Card>)}</div></Card></section></Shell>; }
function TokensPage() { return <Shell><section className="mx-auto max-w-[1720px] p-3"><ColorTypography /><div className="mt-3"><IconSystem /></div><div className="mt-3 grid gap-3 md:grid-cols-4">{motionPresets.slice(0,8).map((m) => <Card key={m.id}><h2 className="font-black">{m.title}</h2><p className="text-xs text-[var(--muted)]">{m.duration}ms · {m.token}</p></Card>)}</div></section></Shell>; }

export function PlatformPage({ kind }: { kind: PageKind }) { if (kind === 'builder') return <Builder />; if (kind === 'marketplace' || kind === 'components' || kind === 'motion') return <Marketplace />; if (kind === 'ai') return <Studio />; if (kind === 'dashboard') return <Dashboard />; if (kind === 'docs') return <Docs />; if (kind === 'assets' || kind === 'tokens' || kind === 'themes' || kind === 'settings') return <TokensPage />; return <Landing />; }
